---
name: Pre-Discussed Issue or Feature Request
about: |-
  Create a new issue or feature request that has been already been
  discussed and approved in the GitHub Discussions section.
---

Discussion Number:

# Additional Information
