on: [push]

name: Flatpak

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-43
      options: --privileged
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0
    # Docker is required by the docker/setup-qemu-action which enables emulation
    - name: Install deps
      run: |
        dnf -y install docker
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        platforms: arm64
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: ghostty.flatpak
        manifest-path: com.mitchellh.ghostty.yml
        branch: tip
        cache-key: flatpak-builder-${{ matrix.arch }}-${{ github.sha }}-v1
        arch: ${{ matrix.arch }}
