on: [push, pull_request]
name: Nix
jobs:
  check-zig-cache-hash:
    runs-on: namespace-profile-ghostty-sm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Nix Cache
        uses: namespacelabs/nscloud-cache-action@v1.1.0
        with:
          path: /nix
      - name: Setup Nix
        uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: ghostty
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          useDaemon: false # sometimes fails on short jobs
      - name: Check Zig cache hash
        run: nix develop -c ./nix/build-support/check-zig-cache-hash.sh
